spring:
  datasource:
    lwzdb001:
      url: jdbc:mysql://127.0.0.1:3306/lwzdb?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
      username: root
      password: feixiong.
      driverClassName: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      useGlobalDataSourceStat: true
      filters: stat,wall,logback
    lwzdb002:
      url: jdbc:mysql://127.0.0.1:3306/lwzdb2?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
      username: root
      password: feixiong.
      driverClassName: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      useGlobalDataSourceStat: true
      filters: stat,wall,logback